/**
 * BDO Mock Data — 本地 UI 開發用
 * 完全唔需要 Supabase 連接
 */
import type { Brand, Category, District, Offer, Tag } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, slug: "dining",     name_tc: "餐飲美食", icon: "🍽️", sort_order: 1 },
  { id: 2, slug: "attraction", name_tc: "主題樂園", icon: "🎡", sort_order: 2 },
  { id: 3, slug: "cinema",     name_tc: "戲院娛樂", icon: "🎬", sort_order: 3 },
  { id: 4, slug: "retail",     name_tc: "零售購物", icon: "🛍️", sort_order: 4 },
  { id: 5, slug: "hotel",      name_tc: "酒店住宿", icon: "🏨", sort_order: 5 },
  { id: 6, slug: "spa",        name_tc: "美容水療", icon: "💆", sort_order: 6 },
  { id: 7, slug: "cafe",       name_tc: "咖啡甜品", icon: "☕", sort_order: 7 },
  { id: 8, slug: "other",      name_tc: "其他優惠", icon: "🎁", sort_order: 8 },
];

export const MOCK_DISTRICTS: District[] = [
  { id: 1, slug: "hk-island",        name_tc: "香港島" },
  { id: 2, slug: "kowloon",          name_tc: "九龍" },
  { id: 3, slug: "new-territories",  name_tc: "新界" },
  { id: 4, slug: "lantau",           name_tc: "大嶼山" },
  { id: 5, slug: "online",           name_tc: "網上 / 全港" },
];

const TAGS: Tag[] = [
  { id: 1, name_tc: "完全免費", slug: "free" },
  { id: 2, name_tc: "免費蛋糕", slug: "free-cake" },
  { id: 3, name_tc: "免費門票", slug: "free-entry" },
  { id: 4, name_tc: "免費禮品", slug: "free-gift" },
  { id: 5, name_tc: "折扣優惠", slug: "discount" },
  { id: 6, name_tc: "會員專屬", slug: "members-only" },
  { id: 7, name_tc: "需要預約", slug: "reservation-required" },
  { id: 8, name_tc: "生日當天", slug: "birthday-day-only" },
  { id: 9, name_tc: "全月有效", slug: "full-month" },
];

const BRANDS: Brand[] = [
  {
    id: "b-001", name_tc: "香港迪士尼樂園", name_en: "Hong Kong Disneyland",
    logo_url: null, website_url: "https://www.hongkongdisneyland.com",
    category_id: 2, district_id: 4, is_verified: true, is_featured: true,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[1], district: MOCK_DISTRICTS[3],
  },
  {
    id: "b-002", name_tc: "海洋公園香港", name_en: "Ocean Park Hong Kong",
    logo_url: null, website_url: "https://www.oceanpark.com.hk",
    category_id: 2, district_id: 1, is_verified: true, is_featured: true,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[1], district: MOCK_DISTRICTS[0],
  },
  {
    id: "b-003", name_tc: "杜莎夫人蠟像館", name_en: "Madame Tussauds HK",
    logo_url: null, website_url: "https://www.madametussauds.com/hong-kong/",
    category_id: 2, district_id: 1, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[1], district: MOCK_DISTRICTS[0],
  },
  {
    id: "b-004", name_tc: "百老匯院線", name_en: "Broadway Circuit",
    logo_url: null, website_url: "https://www.cinema.com.hk",
    category_id: 3, district_id: null, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[2], district: MOCK_DISTRICTS[4],
  },
  {
    id: "b-005", name_tc: "嘉禾院線", name_en: "Golden Harvest",
    logo_url: null, website_url: "https://www.goldenharvest.com",
    category_id: 3, district_id: null, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[2], district: MOCK_DISTRICTS[4],
  },
  {
    id: "b-006", name_tc: "英皇戲院", name_en: "Emperor Cinemas",
    logo_url: null, website_url: "https://www.emperorcinemas.com",
    category_id: 3, district_id: null, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[2], district: MOCK_DISTRICTS[4],
  },
  {
    id: "b-007", name_tc: "大家樂", name_en: "Café de Coral",
    logo_url: null, website_url: "https://www.cafedecoral.com",
    category_id: 1, district_id: null, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[0], district: MOCK_DISTRICTS[4],
  },
  {
    id: "b-008", name_tc: "大快活", name_en: "Fairwood",
    logo_url: null, website_url: "https://www.fairwood.com.hk",
    category_id: 1, district_id: null, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[0], district: MOCK_DISTRICTS[4],
  },
  {
    id: "b-009", name_tc: "美心西餅", name_en: "Maxim's Cakes",
    logo_url: null, website_url: "https://www.maximscakes.com.hk",
    category_id: 7, district_id: null, is_verified: true, is_featured: true,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[6], district: MOCK_DISTRICTS[4],
  },
  {
    id: "b-010", name_tc: "山頂纜車", name_en: "Peak Tram",
    logo_url: null, website_url: "https://www.thepeak.com.hk",
    category_id: 2, district_id: 1, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[1], district: MOCK_DISTRICTS[0],
  },
  {
    id: "b-011", name_tc: "君悅酒店", name_en: "Grand Hyatt Hong Kong",
    logo_url: null, website_url: "https://www.hyatt.com",
    category_id: 5, district_id: 1, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[4], district: MOCK_DISTRICTS[0],
  },
  {
    id: "b-012", name_tc: "The Mira Hong Kong", name_en: "The Mira Hong Kong",
    logo_url: null, website_url: "https://www.themirahotel.com",
    category_id: 5, district_id: 2, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[4], district: MOCK_DISTRICTS[1],
  },
  {
    id: "b-013", name_tc: "UNIQLO", name_en: "UNIQLO",
    logo_url: null, website_url: "https://www.uniqlo.com/hk",
    category_id: 4, district_id: null, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[3], district: MOCK_DISTRICTS[4],
  },
  {
    id: "b-014", name_tc: "昂坪360", name_en: "Ngong Ping 360",
    logo_url: null, website_url: "https://www.np360.com.hk",
    category_id: 2, district_id: 4, is_verified: true, is_featured: false,
    created_at: "2025-01-01", updated_at: "2025-01-01",
    category: MOCK_CATEGORIES[1], district: MOCK_DISTRICTS[3],
  },
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: "o-001", brand_id: "b-001",
    title_tc: "生日免費入場一天（配合酒店套票）",
    short_desc_tc: "訂酒店套票壽星免費入樂園一天",
    description_tc: "凡於生日當月訂購迪士尼樂園酒店套票，壽星可享免費樂園一日票一張。需出示有效身份證明文件核實生日日期。優惠須提前預訂，名額有限。",
    validity_type: "birth_month",
    requirements_tc: "需出示有效身份證明文件核實生日月份。需配合酒店套票使用，不可單獨換領。",
    source_url: "https://www.hongkongdisneyland.com/offers/birthday/",
    is_free: true, is_active: true,
    verified_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[0],
    tags: [TAGS[0], TAGS[2], TAGS[6]],
  },
  {
    id: "o-002", brand_id: "b-002",
    title_tc: "生日免費入場海洋公園",
    short_desc_tc: "生日當天憑身份證免費入場",
    description_tc: "壽星於生日當天可免費入場海洋公園一次，需出示載有出生日期之有效身份證明文件。每位壽星只限換領一次，不可轉讓。",
    validity_type: "birthday_day",
    requirements_tc: "需出示香港身份證或護照。壽星本人使用，每年只限一次。",
    source_url: "https://www.oceanpark.com.hk",
    is_free: true, is_active: true,
    verified_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[1],
    tags: [TAGS[0], TAGS[2], TAGS[7]],
  },
  {
    id: "o-003", brand_id: "b-003",
    title_tc: "生日特價門票 HK$160",
    short_desc_tc: "生日月份特價門票 HK$160（原價 $290）",
    description_tc: "壽星於生日月份內到訪杜莎夫人蠟像館，可享特價門票 HK$160（原價 HK$290），慳番 HK$130！",
    validity_type: "birth_month",
    requirements_tc: "需出示有效身份證明文件核實生日月份。",
    source_url: "https://www.madametussauds.com/hong-kong/",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[2],
    tags: [TAGS[4], TAGS[8]],
  },
  {
    id: "o-004", brand_id: "b-004",
    title_tc: "百老匯生日免費戲票一張",
    short_desc_tc: "會員生日月份免費換領戲票一張",
    description_tc: "百老匯電影會會員於生日當月可免費換領電影票一張，適用於全線百老匯院線（百老匯電影中心、The Cinematheque 等）。",
    validity_type: "birth_month",
    requirements_tc: "需為百老匯電影會會員。登入後於生日月份換領，座位視乎場次供應。",
    source_url: "https://www.cinema.com.hk",
    is_free: true, is_active: true,
    verified_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[3],
    tags: [TAGS[0], TAGS[5], TAGS[8]],
  },
  {
    id: "o-005", brand_id: "b-005",
    title_tc: "嘉禾院線生日月份半價戲票",
    short_desc_tc: "會員生日月份半價戲票",
    description_tc: "嘉禾會員於生日月份可享半價電影票優惠，適用於全線嘉禾院線。",
    validity_type: "birth_month",
    requirements_tc: "需為嘉禾院線會員。不適用於特別場次、IMAX、4DX。每月限換領一次。",
    source_url: "https://www.goldenharvest.com",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[4],
    tags: [TAGS[4], TAGS[5], TAGS[8]],
  },
  {
    id: "o-006", brand_id: "b-006",
    title_tc: "英皇戲院生日免費戲票",
    short_desc_tc: "Club E 會員生日當天免費戲票",
    description_tc: "英皇戲院 Club E 會員於生日當天可免費換領電影票一張，適用於全線英皇戲院。",
    validity_type: "birthday_day",
    requirements_tc: "需為英皇戲院 Club E 會員。於生日當天到戲院服務台出示會員證及身份證換領。",
    source_url: "https://www.emperorcinemas.com",
    is_free: true, is_active: true,
    verified_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[5],
    tags: [TAGS[0], TAGS[2], TAGS[5], TAGS[7]],
  },
  {
    id: "o-007", brand_id: "b-007",
    title_tc: "大家樂 App 生日專屬優惠券",
    short_desc_tc: "App 會員生日月份獲折扣或免費飲品券",
    description_tc: "大家樂 App 會員於生日當月可獲專屬生日優惠券，包括指定套餐折扣或免費飲品，透過 App 自動發放。",
    validity_type: "birth_month",
    requirements_tc: "需下載大家樂 App 並登記會員，完善個人資料（包括生日日期）。",
    source_url: "https://www.cafedecoral.com",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[6],
    tags: [TAGS[4], TAGS[5], TAGS[8]],
  },
  {
    id: "o-008", brand_id: "b-008",
    title_tc: "大快活 App 生日套餐折扣",
    short_desc_tc: "App 會員生日當天套餐折扣",
    description_tc: "大快活 App 會員於生日當天可享指定套餐折扣優惠，透過 App 出示優惠碼使用。",
    validity_type: "birthday_day",
    requirements_tc: "需下載大快活 App 並登記完整個人資料。於生日當天於 App 換領並出示優惠碼。",
    source_url: "https://www.fairwood.com.hk",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[7],
    tags: [TAGS[4], TAGS[5], TAGS[7]],
  },
  {
    id: "o-009", brand_id: "b-009",
    title_tc: "美心西餅生日蛋糕 9 折",
    short_desc_tc: "電子會員生日月份蛋糕 9 折",
    description_tc: "美心西餅電子會員於生日月份購買生日蛋糕可享 9 折優惠，部分款式更有免費刻字服務。",
    validity_type: "birth_month",
    requirements_tc: "需為美心西餅電子會員。於門市出示會員二維碼使用，不可與其他優惠同用。",
    source_url: "https://www.maximscakes.com.hk",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[8],
    tags: [TAGS[1], TAGS[4], TAGS[5], TAGS[8]],
  },
  {
    id: "o-010", brand_id: "b-010",
    title_tc: "山頂纜車生日免費乘搭 + 觀景台",
    short_desc_tc: "生日當天免費纜車往返 + 觀景台入場",
    description_tc: "壽星於生日當天可免費乘搭山頂纜車往返一次，並享 The Peak Tower 觀景台免費入場。",
    validity_type: "birthday_day",
    requirements_tc: "需出示載有出生日期之有效身份證明文件。每人每年只限使用一次。",
    source_url: "https://www.thepeak.com.hk",
    is_free: true, is_active: true,
    verified_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[9],
    tags: [TAGS[0], TAGS[2], TAGS[7]],
  },
  {
    id: "o-011", brand_id: "b-011",
    title_tc: "君悅酒店生日住宿禮遇",
    short_desc_tc: "生日月份住宿升級 + 免費蛋糕",
    description_tc: "壽星於生日月份預訂君悅酒店住宿，可享客房升級、免費生日蛋糕及餐廳優惠等生日禮遇。",
    validity_type: "birth_month",
    requirements_tc: "需提前聯絡酒店預訂並告知為生日住宿。需出示有效身份證明文件。優惠視乎房間供應。",
    source_url: "https://www.hyatt.com/en-US/hotel/china/grand-hyatt-hong-kong",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[10],
    tags: [TAGS[1], TAGS[4], TAGS[6], TAGS[8]],
  },
  {
    id: "o-012", brand_id: "b-012",
    title_tc: "The Mira 生日住宿免費升級",
    short_desc_tc: "生日住宿免費升級 + 蛋糕驚喜",
    description_tc: "壽星於生日當月入住 The Mira Hong Kong，可享免費客房升級、生日蛋糕及 Mira Spa 優惠。",
    validity_type: "birth_month",
    requirements_tc: "需提前告知酒店為生日住宿，並出示身份證明文件核實。升級視乎房間供應。",
    source_url: "https://www.themirahotel.com",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[11],
    tags: [TAGS[1], TAGS[4], TAGS[8]],
  },
  {
    id: "o-013", brand_id: "b-013",
    title_tc: "UNIQLO 會員生日優惠券",
    short_desc_tc: "完善資料後生日月份獲購物優惠券",
    description_tc: "UNIQLO 會員完善個人資料（包括生日）後，可於生日月份獲得專屬生日優惠券，享購物折扣。",
    validity_type: "birth_month",
    requirements_tc: "需為 UNIQLO 會員並完善個人資料。優惠券將於生日月份前發送至登記電郵。",
    source_url: "https://www.uniqlo.com/hk",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[12],
    tags: [TAGS[4], TAGS[5], TAGS[8]],
  },
  {
    id: "o-014", brand_id: "b-014",
    title_tc: "昂坪360生日優惠票價",
    short_desc_tc: "生日月份昂坪360特別票價",
    description_tc: "壽星於生日月份購買昂坪360纜車票可享特別優惠票價，欣賞大嶼山美景同時慶祝生日。",
    validity_type: "birth_month",
    requirements_tc: "需出示載有出生日期之有效身份證明文件。",
    source_url: "https://www.np360.com.hk",
    is_free: false, is_active: true,
    verified_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    expires_at: null, created_at: "2025-01-01", updated_at: "2025-01-01",
    brand: BRANDS[13],
    tags: [TAGS[4], TAGS[8]],
  },
];
